exports.sampleCorpus = [
  'I have a heart condition',
  'I have violent diarrhea',
  'I have to return some video tapes',
  'I have an appointment to get my ringworm checked',
  'I have to attend a funeral',
  'I have family issues',
  'I have an appointment to get waxed',
  'I have to go shave',
  'I have a thing',
  'I can\'t',
  'I can\'t leave my dog alone in the house',
  'I can\'t see',
  'I\'m having an affair',
  'I\'m having my teeth removed',
  'I\'m in love',
  'I\'m in trouble with the law',
  'I\'m pregnant',
  'My mom said no',
  'My mom said I have to mow the lawn',
  'My mom needs me',
  'My dad needs my help',
  'My dad said so',
  'My dad got famous on TikTok',
  'My grandma needs help changing her dentures',
  'My grandma needs her shopping done',
  'My grandma\'s cake got burnt',
  'My grandpa wants to smoke weed',
  'My grandpa is at my house',
  'My grandparents are getting divorced',
  'My grandparents are getting married',
  'My cat is having an abortion',
  'My cat is having a birthday party',
  'My dog needs to go for a walk',
  'My dog is having babies',
  'My water broke',
  'I need to go for a walk',
  'I need to go shopping',
  'I need to replace my fridge with a bigger fridge',
  'I need to do my laundry',
  'I need help',
  'I need to buy more avocados for my toast',
  'I need more bleach, lime, and garbage bags',
  'I need about $3.50'
];

exports.badSampleCorpus = [
  '',
  '<script>console.log(\'hello world\')</script>',
  'My { grandma } needs some document.body',
  'document.body is good for the body',
  'const window = null',
  'need, to, delete, this, comma-filled, phrase',
  'Bad comma at end of phrase,',
  ':::::&@#(!!??',
  'a',
  'there\'s a damn bad word in here',
  'asdjfoiadhscbasdiufbdasiufs adhsfiuasdbhuif uhiuasdbhfiudasbfu',
  '4 double """" 4 single \'\'\'\' 1 %$ two --, are allowed!'
];